<?php

function title_case_menu() {
    $items['title_case'] = array(
        'title' => 'Title Case',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_case_success_page'] = array(
        'title' => 'Success!',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function title_case_form() {
    $form['input_string'] = array(
        '#title' => 'Input',
        '#type' => 'textarea',
        '#description' => t('Please enter a string to be title cased.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'GO!',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {
    $input = $form_state['values']['input_string'];
    $_SESSION['title_cased'] = ucwords($input);
    $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
    return $_SESSION['title_cased'];
}
